I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 11, in script call
    call expression UIreturn
  File "game/scripts/script.rpy", line 11, in script call
    call expression UIreturn
ScriptError: could not find label 'livro_Clicked'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 11, in script call
    call expression UIreturn
  File "renpy/ast.py", line 1490, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/scripts/script.rpy", line 11, in script call
    call expression UIreturn
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'livro_Clicked'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
projeto teste 2 1.0
Wed Jun 29 20:03:47 2022
